# Default values for payments-worker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
serviceAccountName: payments-worker-sa
image:
  repository: bhm7vnpxv6irqcr.azurecr.io/chatservicewebapi
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

service:
  type: ClusterIP
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

env:
  configmap:
    - name: CosmosDBConnection__accountEndpoint
    - name: ClientId
  secret:
    - name: ApplicationInsights__ConnectionString
  values:
    - name: ASPNETCORE_ENVIRONMENT
      value: Production