# Default values for payments-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
serviceAccountName: payments-api-sa
image:
  repository: bhm7vnpxv6irqcr.azurecr.io/chatservicewebapi
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

service:
  type: ClusterIP
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

ingress:
  enabled: true
  protocol: #http | https (set by script)
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
    ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  tls:
  - secretName: tls-prod

env:
  configmap:
    - name: CosmosDBConnection__accountEndpoint
    - name: DatabaseSettings__CustomerContainer
    - name: DatabaseSettings__GlobalIndexContainer
    - name: DatabaseSettings__IsMasterRegion
    - name: DatabaseSettings__MemberContainer
    - name: DatabaseSettings__PaymentsDatabase
    - name: DatabaseSettings__PreferredRegions
    - name: DatabaseSettings__TransactionsContainer
    - name: AnalyticsEngine__OpenAIEndpoint
    - name: AnalyticsEngine__OpenAICompletionsDeployment
    - name: ClientId
  secret:
    - name: AnalyticsEngine__OpenAIKey
    - name: ApplicationInsights__ConnectionString
  values:
    - name: ASPNETCORE_ENVIRONMENT
      value: Production