{{- $name := include "payments-api.fullname" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "payments-api.name" . }}
    chart: {{ template "payments-api.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  AzureWebJobsStorage__accountName: {{ .Values.azureWebJobsStorage.accountName }}
  CoreClaimsCosmosDB__accountEndpoint: {{ .Values.coreClaimsCosmosDb.accountEndpoint }}
  CoreClaimsEventHub__fullyQualifiedNamespace: {{ .Values.coreClaimsEventHub.fullyQualifiedNamespace }}
  BusinessRuleOptions__AutoApproveThreshold: {{ .Values.businessRuleOptions.autoApproveThreshold | quote }}
  BusinessRuleOptions__RequireManagerApproval: {{ .Values.businessRuleOptions.requireManagerApproval | quote }}
  BusinessRuleOptions__DemoMode: {{ .Values.businessRuleOptions.demoMode | quote }}
  BusinessRuleOptions__DemoAdjudicatorId: {{ .Values.businessRuleOptions.demoAdjudicatorId }}
  BusinessRuleOptions__DemoManagerAdjudicatorId: {{ .Values.businessRuleOptions.demoManagerAdjudicatorId }}
  RulesEngine__OpenAIEndpoint: {{ .Values.rulesEngine.openAiEndpoint }}
  RulesEngine__OpenAICompletionsDeployment: {{ .Values.rulesEngine.openAiCompletionsDeployment }}
  ClientId: {{ .Values.azureWorkloadIdentity.apiClientId }}
