{{- $name := include "payments-api.fullname" . -}}

apiVersion: v1
kind: Secret
metadata:
  name: "secret-{{ $name }}"
  labels:
    app: {{ template "payments-api.name" . }}
    chart: {{ template "payments-api.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  AnalyticsEngine__OpenAIKey: {{ .Values.analyticsEngine.openAiKey | b64enc }}
  ApplicationInsights__ConnectionString: {{ .Values.applicationInsights.connectionString | b64enc }}